issue = {
    "id": "123",
    "shortId": "IPE-1",
    "title": "Error #1: This is a test error!",
    "culprit": "SentryCustomError(frontend/src/util)",
    "level": "error",
    "status": "unresolved",
    "statusDetails": {},
    "isPublic": False,
    "platform": "javascript",
    "project": {
        "id": "456",
        "name": "ipe",
        "slug": "ipe",
        "platform": "javascript-react",
    },
    "type": "error",
    "metadata": {
        "value": "This is a test error!",
        "type": "Another Error #1",
        "filename": "/frontend/src/util.ts",
        "function": "SentryCustomError",
        "display_title_with_tree_label": False,
    },
    "numComments": 0,
    "assignedTo": {
        "email": "person@example.com",
        "type": "user",
        "id": "789",
        "name": "Person",
    },
    "isBookmarked": False,
    "isSubscribed": False,
    "hasSeen": False,
    "isUnhandled": False,
    "count": "1",
    "userCount": 1,
    "firstSeen": "2022-04-04T18:17:18.320000Z",
    "lastSeen": "2022-04-04T18:17:18.320000Z",
}

event = {
    "event_id": "def456",
    "platform": issue["platform"],
    "datetime": issue["firstSeen"],
    "culprit": issue["culprit"],
    "metadata": issue["metadata"],
    "title": issue["title"],
    "issue_id": issue["id"],
    "environment": "production",
    "web_url": f"https://sentry.io/organizations/lxyz/issues/{issue['id']}/events/def456/",
    "breadcrumbs": {},
    "contexts": {},
    "sdk": {},
}
